#!/bin/bash
# scripts/kk/export_secrets_local.sh — Extract agent keys from AWS to .env.secrets
# One-time setup for local swarm. Requires AWS CLI with access to kk/* in us-east-1.
#
# Usage:
#   bash scripts/kk/export_secrets_local.sh

set -euo pipefail

REGION="us-east-1"
OUTPUT_FILE=".env.secrets"

echo "[export] Extracting agent secrets from AWS Secrets Manager ($REGION)..."

# Agent name -> env var suffix mapping
declare -A AGENTS=(
    ["kk-coordinator"]="COORDINATOR"
    ["kk-karma-hello"]="KARMA_HELLO"
    ["kk-skill-extractor"]="SKILL_EXTRACTOR"
    ["kk-voice-extractor"]="VOICE_EXTRACTOR"
    ["kk-validator"]="VALIDATOR"
    ["kk-soul-extractor"]="SOUL_EXTRACTOR"
    ["kk-juanjumagalp"]="JUANJUMAGALP"
    ["kk-0xjokker"]="0XJOKKER"
    ["kk-0xyuls"]="0XYULS"
)

# Start file
cat > "$OUTPUT_FILE" << 'HEADER'
# KarmaCadabra Agent Secrets — extracted from AWS Secrets Manager
# Generated by: bash scripts/kk/export_secrets_local.sh
# NEVER commit this file

HEADER

EXTRACTED=0
FAILED=0

for AGENT in "${!AGENTS[@]}"; do
    SUFFIX="${AGENTS[$AGENT]}"
    SECRET_NAME="kk/$AGENT"

    KEY=$(aws secretsmanager get-secret-value \
        --secret-id "$SECRET_NAME" \
        --region "$REGION" \
        --query 'SecretString' \
        --output text 2>/dev/null \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('private_key', d.get('PRIVATE_KEY', '')))" 2>/dev/null) || KEY=""

    if [ -n "$KEY" ]; then
        echo "KK_PRIVATE_KEY_${SUFFIX}=${KEY}" >> "$OUTPUT_FILE"
        echo "  [OK] $AGENT"
        EXTRACTED=$((EXTRACTED + 1))
    else
        echo "KK_PRIVATE_KEY_${SUFFIX}=" >> "$OUTPUT_FILE"
        echo "  [FAIL] $AGENT — could not extract private_key"
        FAILED=$((FAILED + 1))
    fi
done

# Anthropic API key (optional fallback)
echo "" >> "$OUTPUT_FILE"
echo "# LLM Fallbacks" >> "$OUTPUT_FILE"

ANTHROPIC_KEY=$(aws secretsmanager get-secret-value \
    --secret-id "kk/anthropic" \
    --region "$REGION" \
    --query 'SecretString' \
    --output text 2>/dev/null \
| python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('ANTHROPIC_API_KEY', ''))" 2>/dev/null) || ANTHROPIC_KEY=""

if [ -n "$ANTHROPIC_KEY" ]; then
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_KEY}" >> "$OUTPUT_FILE"
    echo "  [OK] anthropic"
else
    echo "ANTHROPIC_API_KEY=" >> "$OUTPUT_FILE"
    echo "  [SKIP] anthropic — not found or empty"
fi

echo "OPENROUTER_API_KEY=" >> "$OUTPUT_FILE"
echo "OPENAI_API_KEY=" >> "$OUTPUT_FILE"

echo ""
echo "[export] Done: $EXTRACTED extracted, $FAILED failed"
echo "[export] Secrets written to $OUTPUT_FILE"
